### ISSUE TITLE
Video control bar can't support locale language switch

### ISSUE THREAD

**Issue by tamama9527** [mikesteele/dual-captions#109]
In version 2.2.1
I choose Traditional Chinese language, but the control bar still English.
![image](https://user-images.githubusercontent.com/22340606/66136691-73f79400-e62e-11e9-9b51-92ab19c5423c.png)
![image](https://user-images.githubusercontent.com/22340606/66136443-106d6680-e62e-11e9-8a73-09ebff4bf557.png)
Can we let the control bar also can be affected by switch locale language

**Comment by mikesteele** [comment]
I started work on this on the branch `translations-in-content-script`. It
will be released soon, I'll ping you on this issue when it is.

**Comment by mikesteele** [comment]
This has been fixed in v2.2.2 and v2.2.3. Thanks again for your help.
