### ISSUE TITLE
Settings don't retain on reload or opening another video

### ISSUE THREAD

**Issue by sankim** [mikesteele/dual-captions#119]
1. Go to Settings, toggle on "Small text"
2. Reload the video
3. Expect that "Small text' would remain toggled on, but it goes back to off (same thing when I open a new YouTube link - I have to turn it on again)

**Comment by mikesteele** [comment]
Hey, is this with the in-video settings panel or the one in the browser
popup? The in-video panel doesn't yet sync across windows yet, the popup
should though.

**Comment by sankim** [comment]
Hey Mike, this is with the settings from the browser I believe: https://www.dropbox.com/s/lokwr69c0zaa19z/Screenshot%202019-12-25%2015.26.56.png?dl=0

**Comment by mikesteele** [comment]
Got it, definitely a bug. I'll check later.

**Comment by mikesteele** [comment]
Hi! The bug was a simple one, I was overwriting the saved settings with the default ones because I change certain settings when the app starts (like UI language) and that triggers a save. The Chrome Web Store takes a few days to approve a new version, but feel free to clone & build the extension if you need it sooner. :-)

**Comment by sankim** [comment]
Awesome thanks!

**Comment by sankim** [comment]
Also, this a lot more complicated, but I noticed that the auto-translated
subtitles aren't available initially - I have to go into the native YT sub
menu, select the auto-translated sub I want, they open up the
extension options where it is then displayed as an option. Have you looked
into making all of them available initially?

**Comment by mikesteele** [comment]
I've thought of that. YouTube lazily loads subtitles, so subtitles for languages are only fetched & loaded once they are selected. For Kanopy (as an example), their app fetches all subtitle languages, so they become instantly available in DC.

**Comment by sankim** [comment]
Cool thanks for the help!

**Comment by mikesteele** [comment]
No prob, thanks for opening an issue. Feel free to write back if you get more ideas for new features / better UX.
