### ISSUE TITLE
Cannot load subtitles into the app

### ISSUE THREAD

**Issue by Karinush** [mikesteele/dual-captions#124]

**Comment by mikesteele** [comment]
Hi! What video site are you trying to use?

**Comment by notyourbuisnes** [comment]
youtube same problem for me

**Comment by mikesteele** [comment]
Thanks for writing in! YouTube changed their site this weekend, I'll fix it this week. Merging this issue into #128

**Comment by mikesteele** [comment]
I've published a fix with version v2.4.3. Chrome Web Store takes a few days to review, so follow #128 for updates.

**Comment by mikesteele** [comment]
`v2.4.3` has been released with the fix. Thanks again for opening an issue.
