### ISSUE TITLE
can not select second subtitle

### ISSUE THREAD

**Issue by QGB** [mikesteele/dual-captions#127]
https://www.youtube.com/watch?v=_ziP_4pouN8
![image](https://user-images.githubusercontent.com/8005654/73832998-3311c500-4844-11ea-810b-35b47665cb22.png)

**Comment by QGB** [comment]
@mikesteele-drizly

**Comment by mikesteele** [comment]
Hi! The issue is that the video you linked uses autogenerated subtitles, which aren't supported. I'm going to close this as there's a pre-existing issue for this #12
