### ISSUE TITLE
⚠️ YouTube not working [2/9/20] - New caption schema

### ISSUE THREAD

**Issue by okarawn** [mikesteele/dual-captions#128]
Hey, firstly ı'm sorry for my bad english.
yesterday i can see double subtitles on youtube, today i can't see double subtitles in the same video today.
https://www.youtube.com/watch?v=rG8jR4h8BtI
thanks for the plugin

**Comment by mikesteele** [comment]
Hi! Thanks for this, looks like YouTube changed their caption schema. I'll fix this this week.

**Comment by mikesteele** [comment]
I have a solution on `issue-128`. I need to do more testing, but you can clone the repo, checkout that branch, and build the extension to use it. I will release it this week.

**Comment by mikesteele** [comment]
I've published a fix with version `v2.4.3`. Chrome Web Store takes a few days to review, so I will keep this issue open until it is live.

**Comment by mikesteele** [comment]
`v2.4.3` has been released with the fix. Thanks again for opening an issue.
