### ISSUE TITLE
issues in fullscreen

### ISSUE THREAD

**Issue by chlo3m0** [mikesteele/dual-captions#130]
when i watch youtube in full screen, it almost completely cuts off the second subtitle, so i have to watch the video in small screen. it's only an issue when the mouse is not active on the screen, as after that the subtitles move down along with it.
![Screen Shot 2020-03-06 at 7 23 42 am](https://user-images.githubusercontent.com/61853112/76035060-7b272300-5f7b-11ea-8b5a-dd8abac3d3a3.png)

**Comment by mikesteele** [comment]
Hi! I'm going to work on a fix to do this automatically, but you can drag the subtitles up with your mouse in the meantime.

**Comment by chlo3m0** [comment]
thank you! (actually, i have that problem with youtube itself where i move subtitles and they move back down to the default place by the next sentence haha)

**Comment by mikesteele** [comment]
I have a version working on the `move-up-captions` branch for YouTube. I'm going to add support for this on Netflix and Kanopy and release soon.

**Comment by hellpanderrr** [comment]
@mikesteele Thanks, I tried to build it and it works.

**Comment by mikesteele** [comment]
Glad to hear it! I'll release it very soon

Le mar. 24 mars 2020 21 h 57, hellpanderrr <notifications@github.com> a
écrit :

**Comment by mikesteele** [comment]
Sorry for the delay with this. (The world is crazy now haha) I just submitted the fix in v2.4.4, which is in review for the Google Web Store now. I'll comment when it is approved and live.
