### ISSUE TITLE
Please adjust the subtitle file

### ISSUE THREAD

**Issue by molkes** [mikesteele/dual-captions#136]
Download the Polish subtitle and  the English subtitle (automatic translation from Polish to English) from [Hiro The Dense - Dense Shonen Protagonist - YouTube](https://www.youtube.com/watch?v=HgKT3DEqCtk).

## Wrong time

The Polish subtitle:

```
7
00:00:40,0100 --> 00:00:43,540
Huh? To znaczy, jestem tu by zabić demona...
```

The `,0100` should be `,100`.

## The automatic translation subtitle should keep empty subtitles

Compared with the Polish subtitle, the English subtitle (automatic translation from Polish to English) is missing the following:

```
109
00:05:59,840 --> 00:06:01,320
 
```

**Comment by mikesteele** [comment]
Hi! Thanks for opening an issue. I'll take a look at this soon, I think it should be easy to fix.

**Comment by mikesteele** [comment]
Is this only causing problems when you download the subtitle files or is it causing problems when on YouTube?

**Comment by molkes** [comment]
It only causes problems when downloading subtitle files. There is no problem playing it locally, I just think the format of the time should be more standard.

I see.
