### ISSUE TITLE
Extension is not working, second language dropdown is empty

### ISSUE THREAD

**Issue by slishnevsky** [mikesteele/dual-captions#148]
When I am on YouTube watching any video with subtitle turned on, the second language selection dropdownbox is empty, I cannot select a second language. Here is the screenshot: https://imgur.com/5PH5ypi

**Comment by mikesteele** [comment]
This is because the video is using automatic captions. I will add the "can't use automated subtitles" error back in the future.

**Comment by mikesteele** [comment]
This is because the video is using automatic captions. I will add the "can't use automated subtitles" error back in the future.
