### ISSUE TITLE
UI Lags in Brave

### ISSUE THREAD

**Issue by tqml** [mikesteele/dual-captions#158]
I noticed the UI has lags in Brave-Browser (which is based on Chromium). Only the UI in the toolbar is affected, the video overlay is totally fine.

## System

dual-captions: Version 2.6.0
OS: macOS 10.15
Brave Browser: Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64)

**Comment by mikesteele** [comment]
Brave isn't a target of this project, unfortunately. You could try the old design (click "Switch back to old design") to see if that is a better experience for you.
