### ISSUE TITLE
feature-request: customizing the subtitle size 

### ISSUE THREAD

**Issue by WiliTest** [mikesteele/dual-captions#169]
It would be great to be able to customize the subtitle font size (they are either too big or too small).

In any case, I thank you very much for sharing your awesome work!

**Comment by mikesteele** [comment]
Hi! This was a great suggestion. I added this in v2.6.1 and just submitted to the Chrome Web Store. It takes some time for it to be approved and be auto-updated on your Chrome, feel free to clone master and follow the README to install locally yourself if you want it now.

**Comment by vesper8** [comment]
@mikesteele I don't know why but it seems like the text size for the 2nd subtitle is still too small even when I put the slider all the way to the left. It ends up being ~25% of the size of the "main" subtitle.. and this is with the slider all the way to the largest size. Am I doing something wrong? Would it be possible to make the size even more customizable so we can make the text even bigger. I'd like to have the 2nd subtitle text to be the same size, or almost, as the main subtitle text.

Many thanks!
