### ISSUE TITLE
size is getting weird

### ISSUE THREAD

**Issue by urhero** [mikesteele/dual-captions#19]
![image](https://user-images.githubusercontent.com/15223405/36948167-df5410e8-2019-11e8-88e1-b3c461672ee2.png)

First of all! I am glad that someone worked on this. But I am having this problem on Netflix. Would be great if you can fix it. Thank you in advance.

**Comment by mikesteele** [comment]
Thanks for filing an issue! 
* Can you send me the video URL? 
* What language are the captions originally in?
* What language did you select for the second caption?

**Comment by mikesteele** [comment]
Ah, I can reproduce this. 

https://www.netflix.com/watch/80004397

Netflix Language: Korean
Subtitle Language: 영어 [CC] (English)
Second Langauge: Korean

I'll look into this ASAP. :-)

**Comment by urhero** [comment]
Thank you so much! You made a great thing!!

**Comment by mikesteele** [comment]
Just an update on this. I have the size issue fixed, but I'm trying to figure out how best to handle this type of captions. In this mode (Korean, English) Netflix uses two caption containers (one per each line of CC) and appending captions underneath looks very crowded. I'll keep thinking about how best to solve this, maybe moving the caption containers up (via `top`), but that seems like a weak solution.

I'll keep you updated :)

**Comment by urhero** [comment]
Hi Mike,

I really appreciate your wonderful work!!
It helps a lot to improve my English via Netflix.
On Netflix it perfectly works but now in Youtube nothing happens when I
turn On.
Please take a look when you have time.
Thank you!!

**Comment by urhero** [comment]
It is
https://www.youtube.com/watch?v=n1ztspdzxA8
and the second language is Korean.

**Comment by mikesteele** [comment]
This video has only automatic captions, and I haven't add support for automatic captions yet (Issue #12) unfortunately. But you should be able to search YouTube and filter by videos with CC and use dual-captions on those videos :)

I hope to add support for automatic captions in the future, keep an eye out! (I also have a redesign coming, let me know what you think when it is released!)
