### ISSUE TITLE
Control Bar - Subtitles - Covered

### ISSUE THREAD

**Issue by gutorml** [mikesteele/dual-captions#24]
Hello, hello! (((:
![untitled](https://user-images.githubusercontent.com/38168053/38523804-9092c048-3c44-11e8-8e2c-afa41bd9829a.jpg)

Is it possible to move the subtitles above the control bar of Netflix? Or remove the visible control bar?

The issue is:
When I stop the video the control bar cover the subtitles and you're obliged to wait for the control bar disappear to be able to read the dual subtitles.

--- I really try to study just waiting for the control bar disappear but take it so long.. (even if the control bar stays just for a couple seconds if you stopped the video all the time this few 'seconds' starts to annoying. haha ---

PS: Many thanks again, you're awesome

**Comment by mikesteele** [comment]
Okay, this is fixed in v1.2.2 which I just uploaded on the Chrome Web Store. Check it out and let me know if you have any more issues :)
