### ISSUE TITLE
Control Bar - Subtitles - Covered (part 2)

### ISSUE THREAD

**Issue by gutorml** [mikesteele/dual-captions#27]
![untitled1](https://user-images.githubusercontent.com/38168053/38561967-5071aa32-3cd1-11e8-890f-b84d708027a9.jpg)

Hii!
I think this issue it is a little bit more complicated. 
Now the captions are covering the second captions. :(

**Comment by mikesteele** [comment]
Can you post the video URL, first caption language, and second caption language?

**Comment by gutorml** [comment]
Anime: Bleach / Ep 1 (one)

URL:
https://www.netflix.com/watch/70176299?trackId=14170286&tctx=1%2C0%2Cc31a8282-5e38-4521-a33c-97161472e550-1181151%2Cab238953-71de-4821-adc6-d3bdd7be9ba2_144539678X3XX1523369320075%2Cab238953-71de-4821-adc6-d3bdd7be9ba2_ROOT

First caption language: English
Second caption language: Portuguese

**Comment by gutorml** [comment]
I don't know what's happen but I'm watching right now One Punch and looks like perfect!
Both captions are above the menu bar. perfect for reading even if you pause the video.

**Comment by mikesteele** [comment]
The issue is that Netflix uses different UIs depending on the video. I don't have a fix for the type used for Bleach yet. (It's the same issue as #19 ) But some videos it will work. I'm trying to find the best way to fix the Bleach issue. I'll keep you updated. :) (Glad you found a video type that works)

**Comment by mikesteele** [comment]
No worries. I don't know of any at the moment. YouTube support is pretty stable though, so if you see movies/shows on YouTube that are subtitled, they will work correctly. :)

**Comment by mikesteele** [comment]
Hi! I'm pretty sure this is fixed in v1.2.4.1. The only problem is that I did a rewrite and a new bug came up. (#31) It's not a big bug so I should fix it soon and then release v1.2.4.1. I'll comment here when I do.  :)

**Comment by gutorml** [comment]
Cool!! Ok, I'll let you know.

Gustavo Ramalho de Almeida

**Comment by mikesteele** [comment]
Hey! Have you noticed any bugs? :-)
