### ISSUE TITLE
Prefer stored settings over default settings

### ISSUE THREAD

**Issue by mikesteele** [mikesteele/dual-captions#46]
The popup will read settings from DC and prefer those over those stored in settings. This is in case different tabs have different settings.

The issue is that there isn't a differentiation between default and user-defined DC settings. I imagine there could be a property created in the DC constructor (eg. `settingsAreDefault`) that is set to false when the settings are updated via user action. When DC sends its state to the popup, the popup should ignore the settings if they are default and prefer those in chrome.storage.

## Current behavior

Open google.com and open the popup. Set second caption language to French. Open a new YouTube tab and open the popup. The popup says the second caption language is English.

## Desired behavior

Open google.com and open the popup. Set second caption language to French. Open a new YouTube tab and open the popup. The popup says the second caption language is French.

**Comment by wendingp** [comment]
Why is this issue closed?

**Comment by wendingp** [comment]
It would be better to save the setting like automatically turn on the second subtitle.

**Comment by mikesteele** [comment]
This _was_ fixed, but I removed it in v1.3.2 because there were issues. I’ll reopen and address after v1.4.0 is released. I put some initial work on branches ‘add-back-storage-middleware’ and ‘background-page-ssot’

**Comment by mikesteele** [comment]
Hey @wendingp ! Just letting you know that this has been released in v1.4.2 on the Chrome Web Store. You can uninstall & reinstall to get the update. Let me know if you run into any bugs with this version. :-)
