### ISSUE TITLE
 Why does my video not show the second subtitle?

### ISSUE THREAD

**Issue by minhdung321** [mikesteele/dual-captions#47]
![screenshot_20180629204625](https://user-images.githubusercontent.com/39442146/42095738-a683967e-7bdd-11e8-872c-10c6a7b5c672.png)

I did exactly as directed but it still does not show the second subtitle. Hope you can fix this bug for me.

**Comment by mikesteele** [comment]
Hi! 

Sorry, but this video has auto-generated captions, which aren't supported at the moment. (See issue #12 and issue #41.) I hope to add support for auto-generated captions in the future, but they are a tough problem to solve.

To find videos that will work with dual-captions, you can filter by Subtitles/CC in a search. 
<img width="988" alt="screen shot 2018-06-29 at 10 34 32 am" src="https://user-images.githubusercontent.com/3904909/42098160-0f6c6522-7b88-11e8-915f-557a8596bf22.png">

- Mike
