### ISSUE TITLE
Subtitles not being shown

### ISSUE THREAD

**Issue by gutorml** [mikesteele/dual-captions#74]
Hello admin,
I hope you are well and having a great day.

Since yesterday I've noticed that when I enable the dual caption, any subtitle is being shown. 
Could you kindly have a look at what it is happening?

I noticed this issue in a series named New Blood, ep 3.

**Comment by deyuzhoucom** [comment]
Same here.

**Comment by mikesteele** [comment]
Sorry guys, I just started a new job. I'll take a look this weekend.

**Comment by gutorml** [comment]
Yesssss, Mike!
Looking forward! Hahaha
And good luck with your new job.

**Comment by mikesteele** [comment]
Hi guys, sorry I didn't get a chance to look into this over the weekend. Life's a bit busy for me right now, but I care and I will get to this.

**Comment by mikesteele** [comment]
I've started work on this on the `v1.6.0` branch.

**Comment by gutorml** [comment]
Thank you, Mike.
Looking forward.
haha

Kindest regards,

*Gustavo Ramalho de Almeida*
Mobile | Whatsapp: +44 7447 791789.

**Comment by mikesteele** [comment]
I have a rough version working on `v1.6.0` if either of you want to try it out. It will only work with Netflix at the moment. You'll need to build the app locally to use it. (See the instructions in the README)

This update removes Google Translate from the extension. I'm sorry if you use Google Translate-d captions, but it's become too tough to maintain. Now, you'll only be able to use captions from the video, and you'll have to tell the extension what language the captions are in. 

I should have a more polished version of this to release in a week or so. Thanks for your patience. :-)

**Comment by gutorml** [comment]
Hey Mike!
Good morning! How are you?

I would like to try this rough version, however, I would need some
instruction in regards to 'how to do it' if you may.
Could you assist me then?

Have a great day, brother.
Kindest regards,

*Gustavo *

**Comment by mikesteele** [comment]
Here is a build:

[build.zip](https://github.com/mikesteele/dual-captions/files/3056800/build.zip)

1. Download & unzip this link ^
2. Go to chrome://extensions
3. Uninstall the current extension
4. Check "Developer mode" in the top-right hand corner.
5. Click "Load unpacked extension" button
6. Choose the unzipped folder

**Comment by mikesteele** [comment]
This has been fixed in v1.6.0, which I uploaded to the Chrome Web Store last night. Your installed version should have auto-updated to the new version. (You can verify in chrome://extensions)

If not, you can re-install it from the Chrome Web Store here: https://chrome.google.com/webstore/detail/two-captions-for-youtube/lpeonmjfimoijceaalocpgjjchocbiap

Thanks for being patient & let me know what you think of this new version. :)

**Comment by deyuzhoucom** [comment]
Thanks for your hard work!!! 😘
