### ISSUE TITLE
Need mouse movement to make secondary subtitle shows

### ISSUE THREAD

**Issue by arman86** [mikesteele/dual-captions#83]
Hi. Again  I am running 1.6 on Netflix with the Club de Cuervos show (https://www.netflix.com/watch/80197454). This time some how (not sure how) both Spanish and English are set. 

However, often times (once every 10 or so lines)  the secondary subtitle does not show up:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/30092819/58386238-56942880-7fb1-11e9-92c7-9b965302efab.png">

I can make the secondary appear by moving the mouse a bit to get something like this:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/30092819/58386247-83484000-7fb1-11e9-8499-7102b5fa31e5.png">

As you may be able to guess, the show does not even need to be running, it can be paused, and moving the mouse still makes the second subtitle appear. This is the latest Chrome (Version 74.0.3729.169 (Official Build) (64-bit)) on Mac OS X.

**Comment by mikesteele** [comment]
Should be fixed in v2, let me know!
